apiVersion: v1
kind: Service
metadata:
  name: configmap-demo
  namespace: common
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: configmap-demo
